kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 81
    hostPort: 81
    protocol: TCP
  - containerPort: 5000
    hostPort: 5000
    protocol: TCP
  - containerPort: 5001
    hostPort: 5001
    protocol: TCP
- role: worker
  extraMounts:
  - containerPath: /tmp/hostpath_pv
    hostPath: /tmp/hostpath_pv
    readOnly: False
- role: worker
  extraMounts:
  - containerPath: /tmp/hostpath_pv
    hostPath: /tmp/hostpath_pv
    readOnly: False
- role: worker
  extraMounts:
  - containerPath: /tmp/hostpath_pv
    hostPath: /tmp/hostpath_pv
    readOnly: False
