apiVersion: v1
kind: PersistentVolume
metadata:
  name: certs-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pod-50g/influxdb/certs"
