kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
 EphemeralContainers: true
networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 5009
    hostPort: 5009
    protocol: TCP
  - containerPort: 5091
    hostPort: 5091
    protocol: TCP
- role: worker
  extraMounts:
  - hostPath: /tmp/hostpath_pv
    containerPath: /tmp/hostpath_pv
- role: worker
  extraMounts:
  - hostPath: /tmp/hostpath_pv
    containerPath: /tmp/hostpath_pv
